Project items
JPPGroup/Common.Backend pull request #7
Opened 2019-11-03 20:27 UTC by MichaelLiddiard

Reworked project system so the majority of physical file code is moved to the clients.

2019-11-04 14:56 UTC, jon-r-abbott requested changes

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ItemModel.cs
> +        public bool LocalOnly { get; set; } = false;
Should the set be private?

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ItemModel.cs
> +        }
These constructors don't smell right. As discussed, no action as work in progress.

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ItemModel.cs
> +        {
Any reason why this constructor isn't check for null parent?

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/ProjectService.cs
> +                var task = await _auth.GetAuthenticatedClient().GetAsync(PROJECT_ENDPOINT);
Not checking HttpResponseMessage for IsSuccessStatusCode. No action at the moment as continue will throw exception.

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/ProjectService.cs
> +                }
As discussed, doesn't feel right as GetProject doesn't hook up the events. No action as wip.

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/ProjectService.cs
> +                var task = await _auth.GetAuthenticatedClient().GetAsync($"{PROJECT_ENDPOINT}/{id}");
Not checking HttpResponseMessage for IsSuccessStatusCode. No action at the moment as continue will throw exception.

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/ProjectService.cs
> +            var task = await _auth.GetAuthenticatedClient().PostAsync($"{ITEM_ENDPOINT}", httpContent);
Not checking HttpResponseMessage for IsSuccessStatusCode. Needs action, as will return even if not successful ItemModel.

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/ProjectService.cs
> +            var task = await _auth.GetAuthenticatedClient().DeleteAsync($"{ITEM_ENDPOINT}/{id}");
task variable unused - remove or discard "_"

Not checking HttpResponseMessage for IsSuccessStatusCode. No action needed at the moment.

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/ProjectService.cs
> +                var task = await _auth.GetAuthenticatedClient().PutAsync(PROJECT_ENDPOINT + $"/{pm.Id}/Favourite", null);
task variable unused - remove or discard "_"

Not checking HttpResponseMessage for IsSuccessStatusCode. No action needed at the moment.

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/ProjectService.cs
> +        public async Task<ItemModel> CreateItem(string name, string physicalname, ItemModel parent, string type)
physicalname - parameter name lowerCamelCase

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/ProjectService.cs
> +            ProjectModel pm = sender as ProjectModel;
Possible null reference

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ProjectModel.cs
> +using DocumentFormat.OpenXml.Spreadsheet;
Clear up unused using directives

2019-11-04 14:56 UTC, jon-r-abbott commented on src/IMessageProvider.cs
> +        Task ShowMessage(string message, string title);
Missing XML comment
Unused - assume this is for later use?

2019-11-04 14:56 UTC, jon-r-abbott commented on src/IMessageProvider.cs
> +        Task<bool> ShowConfirmDialog(string message, string title = "Confirm");
Missing XML comment

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/IProjectService.cs
> +        Task DeleteItem(Guid id);
Missing XML comments

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/IProjectService.cs
> +using System.Text;
Unnecessary using directive

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/IProjectService.cs
> +        Task<ItemModel> CreateItem(string name, string physicalname, ItemModel parent, string type);
physicalname - parameter name lowerCamelCase

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/IPhysicalFactory.cs
> +using System.Text;
Unnecessary using directive

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/IPhysicalFactory.cs
> +        IPhysicalProject CreateProject(ProjectModel projectModel, IProjectService _projects);
Missing XML comments
_projects - parameter name lowerCamelCase

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/IPhysicalItem.cs
> +        ItemModel LogicalItem { get; set; }
Missing XML comments

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/IPhysicalItem.cs
> +using System.Collections.Generic;
Unnecessary using directives

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/IPhysicalProject.cs
> +using System.Threading.Tasks;
Unnecessary using directives

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/IPhysicalProject.cs
> +        IPhysicalItem ConvertLogicalItemToPhysical(ItemModel item);
XML comments?

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ItemModel.cs
> +using DocumentFormat.OpenXml.Office2013.PowerPoint;
Unnecessary using directives

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ItemModel.cs
> +        internal ItemModel(string name, string physicalname, ItemModel parent, string type, bool localOnly)
physicalname - parameter name lowerCamelCase

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ItemModel.cs
> +        public ItemModel(string name, string physicalname, ItemModel parent, string type)
physicalname - parameter name lowerCamelCase

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ItemModel.cs
> +        public ItemModel(string name, string physicalname, ProjectModel parent, string type)
physicalname - parameter name lowerCamelCase

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ProjectModel.cs
> +            if (fullpath.IndexOf(root) != -1)
Assuming case matters?

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ProjectModel.cs
> +                rootPath = fullpath.Remove(0, fullpath.IndexOf(root) + root.Length);
Again assuming case matters?

2019-11-04 14:56 UTC, jon-r-abbott commented on src/Projects/Model/ProjectModel.cs
> +        private ItemModel ParsePathSegments(string[] Path)
Path - parameter name lowerCamelCase

2019-11-04 21:57 UTC, MichaelLiddiard commented on src/Projects/Model/ItemModel.cs
> +        public bool LocalOnly { get; set; } = false;
No, this is intended to be visible to other parts/clients as needed

2019-11-04 22:20 UTC, MichaelLiddiard commented on src/Projects/ProjectService.cs
> +            ProjectModel pm = sender as ProjectModel;
Will throw expection if cast fails

2019-11-05 09:44 UTC, jon-r-abbott approved these changes

2019-11-05 09:44 UTC, merged